config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'vacations#index'
  resources :vacations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vacation.rb
class Vacation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController

  def index
    @vacations = Vacation.all
  end

  def new
    @vacation = Vacation.new
  end

  def create
    Vacation.create(vacation_params)
    redirect_to root_path
  end

  private

  def vacation_params
    params.require(:vacation).permit(:name, :place, :feedback)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'TravelMo', root_path, class: 'navbar-brand' %>


      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item ">
            <%= link_to 'Share Your Own', new_vacation_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>




    <%= yield %>
  </body>
</html>

app/views/vacations/index.html.erb
<% @vacations.each do |vacation| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= vacation.name %></h1>
    <i><%= vacation.place %></i><br />
    <p><%= vacation.feedback %></p><br />
  </div>

 
<% end %>

app/views/vacations/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Vacation Details</h1>
  <%= simple_form_for @vacation do |f| %>
    <%= f.input :name %>
    <%= f.input :place %>
    <%= f.input :feedback %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-warning' %>
  <% end %>
</div>